# coding: utf-8

# flake8: noqa

"""
    Smart Habit Tracker API

    A gamified habit tracker with automated streak protection and consistency analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: candidate@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AnalyticsApi",
    "AuthApi",
    "HabitsApi",
    "SimulationApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "HTTPValidationError",
    "Habit",
    "HabitCreate",
    "LocationInner",
    "LogResponse",
    "LogUpdate",
    "Token",
    "UserCreate",
    "UserResponse",
    "ValidationError",
]

# import apis into sdk package
from openapi_client.api.analytics_api import AnalyticsApi as AnalyticsApi
from openapi_client.api.auth_api import AuthApi as AuthApi
from openapi_client.api.habits_api import HabitsApi as HabitsApi
from openapi_client.api.simulation_api import SimulationApi as SimulationApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.http_validation_error import HTTPValidationError as HTTPValidationError
from openapi_client.models.habit import Habit as Habit
from openapi_client.models.habit_create import HabitCreate as HabitCreate
from openapi_client.models.location_inner import LocationInner as LocationInner
from openapi_client.models.log_response import LogResponse as LogResponse
from openapi_client.models.log_update import LogUpdate as LogUpdate
from openapi_client.models.token import Token as Token
from openapi_client.models.user_create import UserCreate as UserCreate
from openapi_client.models.user_response import UserResponse as UserResponse
from openapi_client.models.validation_error import ValidationError as ValidationError

