"""
    Smart Habit Tracker API

    A gamified habit tracker with automated streak protection and consistency analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: candidate@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "openapi-client"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">= 3.9"
REQUIRES = [
    "urllib3 >= 2.1.0, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2.11",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Smart Habit Tracker API",
    author="Intern Candidate",
    author_email="candidate@example.com",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Smart Habit Tracker API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    A gamified habit tracker with automated streak protection and consistency analytics.
    """,  # noqa: E501
    package_data={"openapi_client": ["py.typed"]},
)
