# coding: utf-8

# flake8: noqa
"""
    Smart Habit Tracker API

    A gamified habit tracker with automated streak protection and consistency analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: candidate@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.http_validation_error import HTTPValidationError
from openapi_client.models.habit import Habit
from openapi_client.models.habit_create import HabitCreate
from openapi_client.models.location_inner import LocationInner
from openapi_client.models.log_response import LogResponse
from openapi_client.models.log_update import LogUpdate
from openapi_client.models.token import Token
from openapi_client.models.user_create import UserCreate
from openapi_client.models.user_response import UserResponse
from openapi_client.models.validation_error import ValidationError

