# coding: utf-8

"""
    Smart Habit Tracker API

    A gamified habit tracker with automated streak protection and consistency analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: candidate@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.habits_api import HabitsApi


class TestHabitsApi(unittest.TestCase):
    """HabitsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HabitsApi()

    def tearDown(self) -> None:
        pass

    def test_add_habit_habits_post(self) -> None:
        """Test case for add_habit_habits_post

        Create New Habit
        """
        pass

    def test_log_habit_habits_id_log_patch(self) -> None:
        """Test case for log_habit_habits_id_log_patch

        Log Habit Completion
        """
        pass

    def test_read_habits_habits_get(self) -> None:
        """Test case for read_habits_habits_get

        Get All User Habits
        """
        pass


if __name__ == '__main__':
    unittest.main()
