# coding: utf-8

"""
    Smart Habit Tracker

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_add_habit_habits_post(self) -> None:
        """Test case for add_habit_habits_post

        Add Habit
        """
        pass

    def test_create_user_users_post(self) -> None:
        """Test case for create_user_users_post

        Create User
        """
        pass

    def test_log_habit_habits_id_log_patch(self) -> None:
        """Test case for log_habit_habits_id_log_patch

        Log Habit
        """
        pass

    def test_login_token_post(self) -> None:
        """Test case for login_token_post

        Login
        """
        pass

    def test_read_habits_habits_get(self) -> None:
        """Test case for read_habits_habits_get

        Read Habits
        """
        pass


if __name__ == '__main__':
    unittest.main()
