# coding: utf-8

"""
    Smart Habit Tracker API

    A gamified habit tracker with automated streak protection and consistency analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: candidate@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.log_response import LogResponse

class TestLogResponse(unittest.TestCase):
    """LogResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LogResponse:
        """Test LogResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LogResponse`
        """
        model = LogResponse()
        if include_optional:
            return LogResponse(
                id = 56,
                habit_id = 56,
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                status = ''
            )
        else:
            return LogResponse(
                id = 56,
                habit_id = 56,
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                status = '',
        )
        """

    def testLogResponse(self):
        """Test LogResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
