# coding: utf-8

"""
    Smart Habit Tracker API

    A gamified habit tracker with automated streak protection and consistency analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: candidate@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.analytics_api import AnalyticsApi


class TestAnalyticsApi(unittest.TestCase):
    """AnalyticsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AnalyticsApi()

    def tearDown(self) -> None:
        pass

    def test_get_habit_history_habits_id_history_get(self) -> None:
        """Test case for get_habit_history_habits_id_history_get

        Get Habit Activity History
        """
        pass


if __name__ == '__main__':
    unittest.main()
