# coding: utf-8

"""
    Smart Habit Tracker API

    A gamified habit tracker with automated streak protection and consistency analytics.

    The version of the OpenAPI document: 1.0.0
    Contact: candidate@example.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_create_user_users_post(self) -> None:
        """Test case for create_user_users_post

        Register New User
        """
        pass

    def test_login_token_post(self) -> None:
        """Test case for login_token_post

        Login for Access Token
        """
        pass


if __name__ == '__main__':
    unittest.main()
